title: Mike Hoolehan
description: My Personal Blog
author: Mike Hoolehan
logo: /static/img/ilikerobots.png
github: https://github.com/ilikerobots
about: Software developer

baseurl: ""
url: "http://www.hoolehan.com/mike"

disqus_shortname: ilikerobots
google_analytics: UA-83216566-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
