title: Mike Hoolehan
description: Mike Hoolehan's Blog
author: Mike Hoolehan
logo: /static/img/ilikerobots.png
github: https://github.com/ilikerobots
about: Software developer

baseurl: ""
url: "https://ilikerobots.github.io"

#disqus_shortname: ilikerobots
google_analytics: UA-83216566-1

share:
  twitter_username: ilikerobotz
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
